version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_brocker
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    mqttx-web:
      image: emqx/mqttx-web
      container_name: mqttx_web
    ports:
      -"8081:80" #interface Web
    depends_on:
      - mqtt
    restart: unless-stopped
